package dev.ohate.wynncraft4j.model.item.query;

public enum ItemIdentifications {
    BASE_HEALTH("baseHealth"),
    BASE_EARTH_DEFENCE("baseEarthDefence"),
    BASE_THUNDER_DEFENCE("baseThunderDefence"),
    DEXTERITY("dexterity"),
    INTELLIGENCE("intelligence"),
    RAW_INTELLIGENCE("rawIntelligence"),
    SPELL_DAMAGE("spellDamage"),
    THUNDER_DAMAGE("thunderDamage"),
    WATER_DAMAGE("waterDamage"),
    BASE_WATER_DEFENCE("baseWaterDefence"),
    BASE_AIR_DEFENCE("baseAirDefence"),
    AGILITY("agility"),
    MAIN_ATTACK_DAMAGE("mainAttackDamage"),
    RAW_MAIN_ATTACK_DAMAGE("rawMainAttackDamage"),
    WALK_SPEED("walkSpeed"),
    XP_BONUS("xpBonus"),
    AIR_DAMAGE("airDamage"),
    WATER_DEFENCE("waterDefence"),
    AIR_DEFENCE("airDefence"),
    BASE_EARTH_DAMAGE("baseEarthDamage"),
    BASE_FIRE_DAMAGE("baseFireDamage"),
    STRENGTH("strength"),
    DEFENCE("defence"),
    MANA_REGEN("manaRegen"),
    MANA_STEAL("manaSteal"),
    EARTH_DAMAGE("earthDamage"),
    FIRE_DAMAGE("fireDamage"),
    RAW_HEALTH("rawHealth"),
    EXPLODING("exploding"),
    BASE_DAMAGE("baseDamage"),
    BASE_THUNDER_DAMAGE("baseThunderDamage"),
    LIFE_STEAL("lifeSteal"),
    REFLECTION("reflection"),
    LOOT_BONUS("lootBonus"),
    POISON("poison"),
    ELEMENTAL_DAMAGE("elementalDamage"),
    RAW_DEFENCE("rawDefence"),
    RAW_AGILITY("rawAgility"),
    HEALTH_REGEN_RAW("healthRegenRaw"),
    RAW_ATTACK_SPEED("rawAttackSpeed"),
    RAW_STRENGTH("rawStrength"),
    HEALTH_REGEN("healthRegen"),
    RAW_SPELL_DAMAGE("rawSpellDamage"),
    THORNS("thorns"),
    THUNDER_DEFENCE("thunderDefence"),
    BASE_FIRE_DEFENCE("baseFireDefence"),
    RAW_DEXTERITY("rawDexterity"),
    BASE_AIR_DAMAGE("baseAirDamage"),
    EARTH_DEFENCE("earthDefence"),
    FIRE_DEFENCE("fireDefence"),
    FOURTH_SPELL_COST("4thSpellCost"),
    RAW_FIRE_DAMAGE("rawFireDamage"),
    RAW1ST_SPELL_COST("raw1stSpellCost"),
    HEALING_EFFICIENCY("healingEfficiency"),
    BASE_WATER_DAMAGE("baseWaterDamage"),
    ELEMENTAL_SPELL_DAMAGE("elementalSpellDamage"),
    THIRD_SPELL_COST("3rdSpellCost"),
    FIRST_SPELL_COST("1stSpellCost"),
    RAW4TH_SPELL_COST("raw4thSpellCost"),
    STEALING("stealing"),
    SECOND_SPELL_COST("2ndSpellCost"),
    RAW_FIRE_MAIN_ATTACK_DAMAGE("rawFireMainAttackDamage"),
    RAW_AIR_MAIN_ATTACK_DAMAGE("rawAirMainAttackDamage"),
    ELEMENTAL_MAIN_ATTACK_DAMAGE("elementalMainAttackDamage"),
    KNOCKBACK("knockback"),
    RAW2ND_SPELL_COST("raw2ndSpellCost"),
    RAW3RD_SPELL_COST("raw3rdSpellCost"),
    THUNDER_MAIN_ATTACK_DAMAGE("thunderMainAttackDamage"),
    RAW_THUNDER_MAIN_ATTACK_DAMAGE("rawThunderMainAttackDamage"),
    ELEMENTAL_DEFENCE("elementalDefence"),
    JUMP_HEIGHT("jumpHeight"),
    NEUTRAL_DAMAGE("neutralDamage"),
    SLOW_ENEMY("slowEnemy"),
    RAW_EARTH_MAIN_ATTACK_DAMAGE("rawEarthMainAttackDamage"),
    SPRINT_REGEN("sprintRegen"),
    RAW_THUNDER_DAMAGE("rawThunderDamage"),
    RAW_WATER_DAMAGE("rawWaterDamage"),
    SPRINT("sprint"),
    FIRE_SPELL_DAMAGE("fireSpellDamage"),
    AIR_SPELL_DAMAGE("airSpellDamage"),
    EARTH_MAIN_ATTACK_DAMAGE("earthMainAttackDamage"),
    WEAKEN_ENEMY("weakenEnemy"),
    AIR_MAIN_ATTACK_DAMAGE("airMainAttackDamage"),
    WATER_SPELL_DAMAGE("waterSpellDamage"),
    RAW_THUNDER_SPELL_DAMAGE("rawThunderSpellDamage"),
    RAW_ELEMENTAL_SPELL_DAMAGE("rawElementalSpellDamage"),
    RAW_AIR_SPELL_DAMAGE("rawAirSpellDamage"),
    THUNDER_SPELL_DAMAGE("thunderSpellDamage"),
    EARTH_SPELL_DAMAGE("earthSpellDamage"),
    RAW_EARTH_DAMAGE("rawEarthDamage"),
    RAW_NEUTRAL_SPELL_DAMAGE("rawNeutralSpellDamage"),
    RAW_DAMAGE("rawDamage"),
    RAW_FIRE_SPELL_DAMAGE("rawFireSpellDamage"),
    NEUTRAL_MAIN_ATTACK_DAMAGE("neutralMainAttackDamage"),
    RAW_WATER_SPELL_DAMAGE("rawWaterSpellDamage"),
    FIRE_MAIN_ATTACK_DAMAGE("fireMainAttackDamage"),
    RAW_ELEMENTAL_DAMAGE("rawElementalDamage"),
    RAW_NEUTRAL_DAMAGE("rawNeutralDamage"),
    RAW_ELEMENTAL_MAIN_ATTACK_DAMAGE("rawElementalMainAttackDamage"),
    DAMAGE("damage"),
    RAW_AIR_DAMAGE("rawAirDamage"),
    RAW_EARTH_SPELL_DAMAGE("rawEarthSpellDamage"),
    RAW_NEUTRAL_MAIN_ATTACK_DAMAGE("rawNeutralMainAttackDamage"),
    LEVELED_XP_BONUS("leveledXpBonus"),
    DAMAGE_FROM_MOBS("damageFromMobs"),
    LEVELED_LOOT_BONUS("leveledLootBonus"),
    GATHER_XP_BONUS("gatherXpBonus"),
    LOOT_QUALITY("lootQuality"),
    GATHER_SPEED("gatherSpeed"),
    RAW_WATER_MAIN_ATTACK_DAMAGE("rawWaterMainAttackDamage");

    private final String id;

    ItemIdentifications(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }

}
